--- #YAML:1.0
name:               Mojolicious-Plugin-EventSource
version:            0.3
abstract:           A plugin to make it eazy to use EventSource with Mojolicious
author:
    - Fernando Corrêa de Oliveira <fco@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  2.61
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
